### ISSUE TITLE
consider not using `master` for setup-node action

### ISSUE THREAD

**Issue by rkzm** [githubtraining/using-github-actions-for-ci#25]
## Bug Report

**Current behavior**
According to best practice for CI we recommend to use explicit versions of actions. major versions.
For setup-action we are using `master`. This is not best practice unless it is done to educate.
 
**Reproduction**
See nodejs.yml workflow file

**Expected behavior**
Remove reference to master and call a version instead
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses

**Comment by mattdavis0351** [comment]
This looks to have been addressed when the starter workflow was updated.  I'm closing this issue as a result.
