### ISSUE TITLE
Use job outputs in place of artifact storage

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/using-github-actions-for-ci#35]
This course uses artifact storage because, at the time we created it, jobs couldn't pass data to each other.

Now, we've got [job outputs](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjobs_idoutputs)! Let's update the course to use these new parameters. 

/cc @mattdavis0351 I'd love your help in making this happen sometime this week -- folks are going to be using this course for Satellite workshops.

**Comment by mattdavis0351** [comment]
@hectorsector  I disagree.  Job outputs are ephemeral in nature and in this course we are storing a fully built artifact.  The entire point of a CI pipeline is to result in a built and tested artifact that you can then do as you wish with.  Making this artifact ephemeral goes against that widely accepted practice.


Job outputs are better suited for passing data between jobs, not long lasting artifacts.

**Comment by hectorsector** [comment]
I haven’t had a chance to play with it enough to know whether it would make sense for this course, but I’ll defer to you. 

@ppremk we’ll keep this course the way it is, see above. 

> That being said, let's add that to the basic workflow course and get that thing primed for Universe.

We don’t have a basic workflow course yet, and I don’t think it’s realistic to get it shipped by Satellite (next week). But we should open an issue in the content repo about it. 

> That way we can demonstrate this and we wouldn't just be using features for the sake of using them.

Who? Me?

![](https://media3.giphy.com/media/S9Vq8w92O0l7bZZaQI/giphy.gif?cid=4d1e4f291b2344adc05537ddcbbd4365c7adffc952c92249&rid=giphy.gif)

**Comment by ppremk** [comment]
The workshop is completed. Thanks y'all for the support in here too ❤️

**Comment by mattdavis0351** [comment]
Since this is not the intended use for job outputs, and this discussion seems resolved, I am closing this issue.  Reopen if need be 😄
