### ISSUE TITLE
Node starter workflow is causing problems

### ISSUE THREAD

**Issue by mattdavis0351** [githubtraining/using-github-actions-for-ci#42]
## Bug Report

The starter workflow for Node.js has changed and because of that the Learning Lab bot is not longer responding the way we expect it to.

Further troubleshooting is needed to figure out exactly what is missing or changed.  This is coming from the community forum.

**Comment by mattdavis0351** [comment]
this looks to be related to #41

**Comment by ntaranov** [comment]
Do you mean the discussion?
https://github.community/t/github-actions-for-ci-stucked-on-step-1/115646/3

If so, this looks like issue #11

**Comment by mattdavis0351** [comment]
Issue has been resolved in #41 and #43
